[OK]#[OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]_[OK]a[OK]l[OK]l[OK]_[OK]v[OK]i[OK]s[OK]u[OK]a[OK]l[OK]s[OK].[OK]p[OK]y[OK]
[OK]"[OK]"[OK]"[OK]
[OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]v[OK]i[OK]s[OK]u[OK]a[OK]l[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK] [OK]f[OK]o[OK]r[OK] [OK]R[OK]E[OK]A[OK]D[OK]M[OK]E[OK] [OK]s[OK]h[OK]o[OK]w[OK]c[OK]a[OK]s[OK]e[OK]
[OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]s[OK] [OK]a[OK]l[OK]l[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK] [OK]n[OK]e[OK]e[OK]d[OK]e[OK]d[OK] [OK]f[OK]o[OK]r[OK] [OK]a[OK] [OK]v[OK]i[OK]s[OK]u[OK]a[OK]l[OK]l[OK]y[OK] [OK]s[OK]t[OK]u[OK]n[OK]n[OK]i[OK]n[OK]g[OK] [OK]p[OK]r[OK]o[OK]j[OK]e[OK]c[OK]t[OK] [OK]p[OK]r[OK]e[OK]s[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]
[OK]"[OK]"[OK]"[OK]
[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]n[OK]u[OK]m[OK]p[OK]y[OK] [OK]a[OK]s[OK] [OK]n[OK]p[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]m[OK]a[OK]t[OK]p[OK]l[OK]o[OK]t[OK]l[OK]i[OK]b[OK].[OK]p[OK]y[OK]p[OK]l[OK]o[OK]t[OK] [OK]a[OK]s[OK] [OK]p[OK]l[OK]t[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]y[OK]s[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]o[OK]s[OK]
[OK]
[OK]s[OK]y[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]i[OK]n[OK]s[OK]e[OK]r[OK]t[OK]([OK]0[OK],[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]j[OK]o[OK]i[OK]n[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK],[OK] [OK]'[OK]s[OK]r[OK]c[OK]'[OK])[OK])[OK]
[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]d[OK]f[OK]t[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]d[OK]f[OK]t[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]f[OK]f[OK]t[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]f[OK]f[OK]t[OK],[OK] [OK]f[OK]f[OK]t[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]t[OK]i[OK]v[OK]e[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]r[OK]e[OK]c[OK]t[OK]a[OK]n[OK]g[OK]u[OK]l[OK]a[OK]r[OK],[OK] [OK]h[OK]a[OK]n[OK]n[OK],[OK] [OK]h[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]s[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]w[OK]o[OK]_[OK]t[OK]o[OK]n[OK]e[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]s[OK]s[OK]e[OK]d[OK]_[OK]s[OK]e[OK]n[OK]s[OK]i[OK]n[OK]g[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]_[OK]s[OK]e[OK]n[OK]s[OK]i[OK]n[OK]g[OK]_[OK]m[OK]a[OK]t[OK]r[OK]i[OK]x[OK],[OK] [OK]m[OK]a[OK]t[OK]c[OK]h[OK]i[OK]n[OK]g[OK]_[OK]p[OK]u[OK]r[OK]s[OK]u[OK]i[OK]t[OK],[OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]f[OK]r[OK]o[OK]m[OK]_[OK]s[OK]p[OK]a[OK]r[OK]s[OK]e[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]m[OK]e[OK]t[OK]r[OK]i[OK]c[OK]s[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]p[OK]e[OK]c[OK]t[OK]r[OK]a[OK]l[OK]_[OK]e[OK]n[OK]t[OK]r[OK]o[OK]p[OK]y[OK],[OK] [OK]p[OK]e[OK]a[OK]k[OK]_[OK]t[OK]o[OK]_[OK]s[OK]i[OK]d[OK]e[OK]l[OK]o[OK]b[OK]e[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]
[OK]
[OK]#[OK] [OK]E[OK]n[OK]s[OK]u[OK]r[OK]e[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK] [OK]d[OK]i[OK]r[OK]e[OK]c[OK]t[OK]o[OK]r[OK]y[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]s[OK]
[OK]o[OK]s[OK].[OK]m[OK]a[OK]k[OK]e[OK]d[OK]i[OK]r[OK]s[OK]([OK]"[OK]p[OK]l[OK]o[OK]t[OK]s[OK]"[OK],[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]_[OK]o[OK]k[OK]=[OK]T[OK]r[OK]u[OK]e[OK])[OK]
[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]7[OK]0[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK]G[OK]E[OK]N[OK]E[OK]R[OK]A[OK]T[OK]I[OK]N[OK]G[OK] [OK]C[OK]O[OK]M[OK]P[OK]R[OK]E[OK]H[OK]E[OK]N[OK]S[OK]I[OK]V[OK]E[OK] [OK]V[OK]I[OK]S[OK]U[OK]A[OK]L[OK]I[OK]Z[OK]A[OK]T[OK]I[OK]O[OK]N[OK] [OK]S[OK]U[OK]I[OK]T[OK]E[OK]"[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]7[OK]0[OK])[OK]
[OK]
[OK]#[OK] [OK]S[OK]e[OK]t[OK] [OK]c[OK]o[OK]n[OK]s[OK]i[OK]s[OK]t[OK]e[OK]n[OK]t[OK] [OK]s[OK]t[OK]y[OK]l[OK]e[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]t[OK]y[OK]l[OK]e[OK].[OK]u[OK]s[OK]e[OK]([OK]'[OK]s[OK]e[OK]a[OK]b[OK]o[OK]r[OK]n[OK]-[OK]v[OK]0[OK]_[OK]8[OK]-[OK]d[OK]a[OK]r[OK]k[OK]g[OK]r[OK]i[OK]d[OK]'[OK])[OK]
[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK] [OK]=[OK] [OK][[OK]'[OK]#[OK]2[OK]E[OK]8[OK]6[OK]A[OK]B[OK]'[OK],[OK] [OK]'[OK]#[OK]A[OK]2[OK]3[OK]B[OK]7[OK]2[OK]'[OK],[OK] [OK]'[OK]#[OK]F[OK]1[OK]8[OK]F[OK]0[OK]1[OK]'[OK],[OK] [OK]'[OK]#[OK]C[OK]7[OK]3[OK]E[OK]1[OK]D[OK]'[OK],[OK] [OK]'[OK]#[OK]6[OK]A[OK]9[OK]9[OK]4[OK]E[OK]'[OK]][OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]1[OK].[OK] [OK]F[OK]F[OK]T[OK] [OK]C[OK]O[OK]M[OK]P[OK]L[OK]E[OK]X[OK]I[OK]T[OK]Y[OK] [OK]C[OK]O[OK]M[OK]P[OK]A[OK]R[OK]I[OK]S[OK]O[OK]N[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]1[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]F[OK]F[OK]T[OK] [OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]i[OK]t[OK]y[OK] [OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]s[OK]i[OK]z[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]2[OK]*[OK]*[OK]n[OK] [OK]f[OK]o[OK]r[OK] [OK]n[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]4[OK],[OK] [OK]1[OK]1[OK])[OK]][OK] [OK] [OK]#[OK] [OK]1[OK]6[OK] [OK]t[OK]o[OK] [OK]1[OK]0[OK]2[OK]4[OK]
[OK]d[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK] [OK]=[OK] [OK][[OK]n[OK]*[OK]*[OK]2[OK] [OK]f[OK]o[OK]r[OK] [OK]n[OK] [OK]i[OK]n[OK] [OK]s[OK]i[OK]z[OK]e[OK]s[OK]][OK]
[OK]f[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK] [OK]=[OK] [OK][[OK]n[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]l[OK]o[OK]g[OK]2[OK]([OK]n[OK])[OK] [OK]f[OK]o[OK]r[OK] [OK]n[OK] [OK]i[OK]n[OK] [OK]s[OK]i[OK]z[OK]e[OK]s[OK]][OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]([OK]a[OK]x[OK]1[OK],[OK] [OK]a[OK]x[OK]2[OK])[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]1[OK],[OK] [OK]2[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]4[OK],[OK] [OK]5[OK])[OK])[OK]
[OK]
[OK]#[OK] [OK]L[OK]i[OK]n[OK]e[OK]a[OK]r[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]
[OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]s[OK]i[OK]z[OK]e[OK]s[OK],[OK] [OK]d[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]D[OK]F[OK]T[OK]:[OK] [OK]O[OK]([OK]N[OK]²[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]s[OK]i[OK]z[OK]e[OK]s[OK],[OK] [OK]f[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK],[OK] [OK]'[OK]s[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]F[OK]F[OK]T[OK]:[OK] [OK]O[OK]([OK]N[OK] [OK]l[OK]o[OK]g[OK] [OK]N[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]L[OK]e[OK]n[OK]g[OK]t[OK]h[OK] [OK]([OK]N[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]O[OK]p[OK]e[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]A[OK]l[OK]g[OK]o[OK]r[OK]i[OK]t[OK]h[OK]m[OK] [OK]C[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]i[OK]t[OK]y[OK] [OK]([OK]L[OK]i[OK]n[OK]e[OK]a[OK]r[OK] [OK]S[OK]c[OK]a[OK]l[OK]e[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]#[OK] [OK]L[OK]o[OK]g[OK]-[OK]l[OK]o[OK]g[OK] [OK]s[OK]c[OK]a[OK]l[OK]e[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]o[OK]g[OK]l[OK]o[OK]g[OK]([OK]s[OK]i[OK]z[OK]e[OK]s[OK],[OK] [OK]d[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]D[OK]F[OK]T[OK]:[OK] [OK]O[OK]([OK]N[OK]²[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]o[OK]g[OK]l[OK]o[OK]g[OK]([OK]s[OK]i[OK]z[OK]e[OK]s[OK],[OK] [OK]f[OK]f[OK]t[OK]_[OK]o[OK]p[OK]s[OK],[OK] [OK]'[OK]s[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]F[OK]F[OK]T[OK]:[OK] [OK]O[OK]([OK]N[OK] [OK]l[OK]o[OK]g[OK] [OK]N[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]L[OK]e[OK]n[OK]g[OK]t[OK]h[OK] [OK]([OK]N[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]O[OK]p[OK]e[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]A[OK]l[OK]g[OK]o[OK]r[OK]i[OK]t[OK]h[OK]m[OK] [OK]C[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]i[OK]t[OK]y[OK] [OK]([OK]L[OK]o[OK]g[OK]-[OK]L[OK]o[OK]g[OK] [OK]S[OK]c[OK]a[OK]l[OK]e[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK],[OK] [OK]w[OK]h[OK]i[OK]c[OK]h[OK]=[OK]'[OK]b[OK]o[OK]t[OK]h[OK]'[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]0[OK]0[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]i[OK]t[OK]y[OK]_[OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]0[OK]0[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]i[OK]t[OK]y[OK]_[OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]2[OK].[OK] [OK]W[OK]I[OK]N[OK]D[OK]O[OK]W[OK] [OK]F[OK]U[OK]N[OK]C[OK]T[OK]I[OK]O[OK]N[OK]S[OK] [OK]S[OK]H[OK]O[OK]W[OK]C[OK]A[OK]S[OK]E[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]2[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]s[OK]h[OK]o[OK]w[OK]c[OK]a[OK]s[OK]e[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]N[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK] [OK]=[OK] [OK]2[OK]5[OK]6[OK]
[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK]_[OK]d[OK]i[OK]c[OK]t[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]R[OK]e[OK]c[OK]t[OK]a[OK]n[OK]g[OK]u[OK]l[OK]a[OK]r[OK]'[OK]:[OK] [OK]r[OK]e[OK]c[OK]t[OK]a[OK]n[OK]g[OK]u[OK]l[OK]a[OK]r[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]H[OK]a[OK]n[OK]n[OK]'[OK]:[OK] [OK]h[OK]a[OK]n[OK]n[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]H[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]'[OK]:[OK] [OK]h[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK])[OK]
[OK]}[OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]a[OK]x[OK]e[OK]s[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]2[OK],[OK] [OK]3[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]5[OK],[OK] [OK]8[OK])[OK])[OK]
[OK]
[OK]f[OK]o[OK]r[OK] [OK]i[OK]d[OK]x[OK],[OK] [OK]([OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK])[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]u[OK]m[OK]e[OK]r[OK]a[OK]t[OK]e[OK]([OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK]_[OK]d[OK]i[OK]c[OK]t[OK].[OK]i[OK]t[OK]e[OK]m[OK]s[OK]([OK])[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]i[OK]m[OK]e[OK] [OK]d[OK]o[OK]m[OK]a[OK]i[OK]n[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]0[OK],[OK] [OK]i[OK]d[OK]x[OK]][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]i[OK]d[OK]x[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]f[OK]'[OK]{[OK]n[OK]a[OK]m[OK]e[OK]}[OK] [OK]W[OK]i[OK]n[OK]d[OK]o[OK]w[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]a[OK]m[OK]p[OK]l[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]A[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]t[OK]i[OK]m[OK]e[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]i[OK]m[OK]([OK]-[OK]0[OK].[OK]1[OK],[OK] [OK]1[OK].[OK]1[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]r[OK]e[OK]s[OK]p[OK]o[OK]n[OK]s[OK]e[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]1[OK],[OK] [OK]i[OK]d[OK]x[OK]][OK]
[OK] [OK] [OK] [OK] [OK]W[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]f[OK]f[OK]t[OK].[OK]f[OK]f[OK]t[OK]([OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK],[OK] [OK]2[OK]0[OK]4[OK]8[OK])[OK]
[OK] [OK] [OK] [OK] [OK]W[OK]_[OK]d[OK]b[OK] [OK]=[OK] [OK]2[OK]0[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]l[OK]o[OK]g[OK]1[OK]0[OK]([OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]W[OK][[OK]:[OK]1[OK]0[OK]2[OK]4[OK]][OK])[OK] [OK]/[OK] [OK]n[OK]p[OK].[OK]m[OK]a[OK]x[OK]([OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]W[OK])[OK])[OK] [OK]+[OK] [OK]1[OK]e[OK]-[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]f[OK]r[OK]e[OK]q[OK]s[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]l[OK]i[OK]n[OK]s[OK]p[OK]a[OK]c[OK]e[OK]([OK]0[OK],[OK] [OK]0[OK].[OK]5[OK],[OK] [OK]1[OK]0[OK]2[OK]4[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK],[OK] [OK]W[OK]_[OK]d[OK]b[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]i[OK]d[OK]x[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]f[OK]'[OK]{[OK]n[OK]a[OK]m[OK]e[OK]}[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]R[OK]e[OK]s[OK]p[OK]o[OK]n[OK]s[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]e[OK]d[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]M[OK]a[OK]g[OK]n[OK]i[OK]t[OK]u[OK]d[OK]e[OK] [OK]([OK]d[OK]B[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]i[OK]m[OK]([OK]-[OK]8[OK]0[OK],[OK] [OK]5[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]_[OK]f[OK]r[OK]e[OK]q[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]3[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]_[OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK]_[OK]s[OK]h[OK]o[OK]w[OK]c[OK]a[OK]s[OK]e[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]3[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]_[OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK]_[OK]s[OK]h[OK]o[OK]w[OK]c[OK]a[OK]s[OK]e[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]3[OK].[OK] [OK]C[OK]O[OK]M[OK]P[OK]R[OK]E[OK]S[OK]S[OK]E[OK]D[OK] [OK]S[OK]E[OK]N[OK]S[OK]I[OK]N[OK]G[OK] [OK]S[OK]U[OK]C[OK]C[OK]E[OK]S[OK]S[OK] [OK]R[OK]A[OK]T[OK]E[OK] [OK]v[OK]s[OK] [OK]S[OK]A[OK]M[OK]P[OK]L[OK]I[OK]N[OK]G[OK] [OK]R[OK]A[OK]T[OK]I[OK]O[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]3[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]C[OK]S[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]r[OK]a[OK]t[OK]e[OK] [OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]N[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]
[OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]s[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]l[OK]i[OK]n[OK]s[OK]p[OK]a[OK]c[OK]e[OK]([OK]0[OK].[OK]2[OK],[OK] [OK]0[OK].[OK]9[OK],[OK] [OK]8[OK])[OK]
[OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]_[OK]r[OK]a[OK]t[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]][OK]
[OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]=[OK] [OK][[OK]][OK]
[OK]
[OK]f[OK]o[OK]r[OK] [OK]r[OK]a[OK]t[OK]i[OK]o[OK] [OK]i[OK]n[OK] [OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]s[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]M[OK] [OK]=[OK] [OK]i[OK]n[OK]t[OK]([OK]N[OK] [OK]*[OK] [OK]r[OK]a[OK]t[OK]i[OK]o[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]e[OK]s[OK] [OK]=[OK] [OK]0[OK]
[OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]_[OK]l[OK]i[OK]s[OK]t[OK] [OK]=[OK] [OK][[OK]][OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]r[OK]i[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]2[OK]0[OK])[OK]:[OK] [OK] [OK]#[OK] [OK]2[OK]0[OK] [OK]t[OK]r[OK]i[OK]a[OK]l[OK]s[OK] [OK]p[OK]e[OK]r[OK] [OK]r[OK]a[OK]t[OK]i[OK]o[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]p[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]s[OK]e[OK]e[OK]d[OK]([OK]t[OK]r[OK]i[OK]a[OK]l[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK] [OK]s[OK]p[OK]a[OK]r[OK]s[OK]e[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]1[OK],[OK] [OK]f[OK]2[OK] [OK]=[OK] [OK]1[OK]0[OK],[OK] [OK]2[OK]5[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]N[OK])[OK] [OK]/[OK] [OK]N[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]x[OK]_[OK]t[OK]r[OK]u[OK]e[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]c[OK]o[OK]s[OK]([OK]2[OK]*[OK]n[OK]p[OK].[OK]p[OK]i[OK]*[OK]f[OK]1[OK]*[OK]t[OK])[OK] [OK]+[OK] [OK]0[OK].[OK]5[OK]*[OK]n[OK]p[OK].[OK]c[OK]o[OK]s[OK]([OK]2[OK]*[OK]n[OK]p[OK].[OK]p[OK]i[OK]*[OK]f[OK]2[OK]*[OK]t[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]a[OK]m[OK]p[OK]l[OK]e[OK] [OK]a[OK]n[OK]d[OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]s[OK]o[OK]r[OK]t[OK]([OK]n[OK]p[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]N[OK],[OK] [OK]M[OK],[OK] [OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]=[OK]F[OK]a[OK]l[OK]s[OK]e[OK])[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]y[OK] [OK]=[OK] [OK]x[OK]_[OK]t[OK]r[OK]u[OK]e[OK][[OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK]][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]o[OK]p[OK]e[OK]r[OK]a[OK]t[OK]o[OK]r[OK] [OK]=[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]_[OK]s[OK]e[OK]n[OK]s[OK]i[OK]n[OK]g[OK]_[OK]m[OK]a[OK]t[OK]r[OK]i[OK]x[OK]([OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK],[OK] [OK]N[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]_[OK]h[OK]a[OK]t[OK] [OK]=[OK] [OK]m[OK]a[OK]t[OK]c[OK]h[OK]i[OK]n[OK]g[OK]_[OK]p[OK]u[OK]r[OK]s[OK]u[OK]i[OK]t[OK]([OK]y[OK],[OK] [OK]o[OK]p[OK]e[OK]r[OK]a[OK]t[OK]o[OK]r[OK],[OK] [OK]m[OK]a[OK]x[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]=[OK]2[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]x[OK]_[OK]r[OK]e[OK]c[OK]o[OK]n[OK] [OK]=[OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]f[OK]r[OK]o[OK]m[OK]_[OK]s[OK]p[OK]a[OK]r[OK]s[OK]e[OK]([OK]s[OK]_[OK]h[OK]a[OK]t[OK],[OK] [OK]N[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]l[OK]i[OK]n[OK]a[OK]l[OK]g[OK].[OK]n[OK]o[OK]r[OK]m[OK]([OK]x[OK]_[OK]t[OK]r[OK]u[OK]e[OK] [OK]-[OK] [OK]x[OK]_[OK]r[OK]e[OK]c[OK]o[OK]n[OK])[OK] [OK]/[OK] [OK]n[OK]p[OK].[OK]l[OK]i[OK]n[OK]a[OK]l[OK]g[OK].[OK]n[OK]o[OK]r[OK]m[OK]([OK]x[OK]_[OK]t[OK]r[OK]u[OK]e[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]_[OK]l[OK]i[OK]s[OK]t[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]e[OK]r[OK]r[OK]o[OK]r[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK] [OK]<[OK] [OK]0[OK].[OK]3[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]e[OK]s[OK] [OK]+[OK]=[OK] [OK]1[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]_[OK]r[OK]a[OK]t[OK]e[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]e[OK]s[OK] [OK]/[OK] [OK]2[OK]0[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]e[OK]r[OK]r[OK]o[OK]r[OK]_[OK]l[OK]i[OK]s[OK]t[OK])[OK])[OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]([OK]a[OK]x[OK]1[OK],[OK] [OK]a[OK]x[OK]2[OK])[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]1[OK],[OK] [OK]2[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]4[OK],[OK] [OK]5[OK])[OK])[OK]
[OK]
[OK]#[OK] [OK]S[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]r[OK]a[OK]t[OK]e[OK]
[OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]s[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]_[OK]r[OK]a[OK]t[OK]e[OK]s[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]2[OK]][OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]3[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]a[OK]x[OK]h[OK]l[OK]i[OK]n[OK]e[OK]([OK]y[OK]=[OK]9[OK]0[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]r[OK]e[OK]d[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]9[OK]0[OK]%[OK] [OK]S[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]T[OK]h[OK]r[OK]e[OK]s[OK]h[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]f[OK]i[OK]l[OK]l[OK]_[OK]b[OK]e[OK]t[OK]w[OK]e[OK]e[OK]n[OK]([OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]s[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]0[OK],[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]_[OK]r[OK]a[OK]t[OK]e[OK]s[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]2[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]2[OK]][OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]R[OK]a[OK]t[OK]e[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]C[OK]S[OK] [OK]R[OK]e[OK]c[OK]o[OK]v[OK]e[OK]r[OK]y[OK] [OK]S[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]v[OK]s[OK].[OK] [OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]
[OK]#[OK] [OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]
[OK]a[OK]x[OK]2[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]r[OK]a[OK]t[OK]i[OK]o[OK]s[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK],[OK] [OK]'[OK]s[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]3[OK]][OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]3[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]a[OK]x[OK]h[OK]l[OK]i[OK]n[OK]e[OK]([OK]y[OK]=[OK]0[OK].[OK]0[OK]5[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]g[OK]r[OK]e[OK]e[OK]n[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]<[OK]5[OK]%[OK] [OK]E[OK]r[OK]r[OK]o[OK]r[OK] [OK]T[OK]a[OK]r[OK]g[OK]e[OK]t[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]o[OK]r[OK]m[OK]a[OK]l[OK]i[OK]z[OK]e[OK]d[OK] [OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]E[OK]r[OK]r[OK]o[OK]r[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]E[OK]r[OK]r[OK]o[OK]r[OK] [OK]v[OK]s[OK].[OK] [OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]4[OK]_[OK]c[OK]s[OK]_[OK]p[OK]e[OK]r[OK]f[OK]o[OK]r[OK]m[OK]a[OK]n[OK]c[OK]e[OK]_[OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]4[OK]_[OK]c[OK]s[OK]_[OK]p[OK]e[OK]r[OK]f[OK]o[OK]r[OK]m[OK]a[OK]n[OK]c[OK]e[OK]_[OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]4[OK].[OK] [OK]S[OK]P[OK]E[OK]C[OK]T[OK]R[OK]A[OK]L[OK] [OK]L[OK]E[OK]A[OK]K[OK]A[OK]G[OK]E[OK] [OK]C[OK]O[OK]M[OK]P[OK]A[OK]R[OK]I[OK]S[OK]O[OK]N[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]4[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]s[OK]p[OK]e[OK]c[OK]t[OK]r[OK]a[OK]l[OK] [OK]l[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK] [OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]f[OK]s[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]0[OK]
[OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]1[OK].[OK]0[OK]
[OK]N[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]=[OK] [OK]i[OK]n[OK]t[OK]([OK]f[OK]s[OK] [OK]*[OK] [OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK])[OK]
[OK]f[OK] [OK]=[OK] [OK]5[OK]5[OK].[OK]7[OK] [OK] [OK]#[OK] [OK]N[OK]o[OK]n[OK]-[OK]i[OK]n[OK]t[OK]e[OK]g[OK]e[OK]r[OK] [OK]b[OK]i[OK]n[OK] [OK]f[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK]
[OK]
[OK]t[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]N[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK])[OK] [OK]/[OK] [OK]f[OK]s[OK]
[OK]x[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]s[OK]i[OK]n[OK]([OK]2[OK]*[OK]n[OK]p[OK].[OK]p[OK]i[OK]*[OK]f[OK]*[OK]t[OK])[OK]
[OK]
[OK]N[OK]_[OK]w[OK]i[OK]n[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]0[OK]
[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK]_[OK]d[OK]i[OK]c[OK]t[OK]_[OK]l[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]R[OK]e[OK]c[OK]t[OK]a[OK]n[OK]g[OK]u[OK]l[OK]a[OK]r[OK]'[OK]:[OK] [OK]r[OK]e[OK]c[OK]t[OK]a[OK]n[OK]g[OK]u[OK]l[OK]a[OK]r[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]H[OK]a[OK]n[OK]n[OK]'[OK]:[OK] [OK]h[OK]a[OK]n[OK]n[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK]'[OK]H[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]'[OK]:[OK] [OK]h[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK])[OK]
[OK]}[OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]a[OK]x[OK]e[OK]s[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]3[OK],[OK] [OK]1[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]2[OK],[OK] [OK]1[OK]0[OK])[OK])[OK]
[OK]
[OK]f[OK]o[OK]r[OK] [OK]i[OK]d[OK]x[OK],[OK] [OK]([OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK])[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]u[OK]m[OK]e[OK]r[OK]a[OK]t[OK]e[OK]([OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK]_[OK]d[OK]i[OK]c[OK]t[OK]_[OK]l[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK].[OK]i[OK]t[OK]e[OK]m[OK]s[OK]([OK])[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]i[OK]d[OK]x[OK]][OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]x[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]e[OK]d[OK] [OK]=[OK] [OK]x[OK] [OK]*[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]
[OK] [OK] [OK] [OK] [OK]X[OK] [OK]=[OK] [OK]d[OK]f[OK]t[OK]([OK]x[OK]_[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]e[OK]d[OK])[OK]
[OK] [OK] [OK] [OK] [OK]f[OK]r[OK]e[OK]q[OK]s[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]N[OK]_[OK]w[OK]i[OK]n[OK])[OK] [OK]*[OK] [OK]f[OK]s[OK] [OK]/[OK] [OK]N[OK]_[OK]w[OK]i[OK]n[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]m[OK]a[OK]g[OK]_[OK]d[OK]b[OK] [OK]=[OK] [OK]2[OK]0[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]l[OK]o[OK]g[OK]1[OK]0[OK]([OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]X[OK][[OK]:[OK]N[OK]_[OK]w[OK]i[OK]n[OK]/[OK]/[OK]2[OK]][OK])[OK] [OK]/[OK] [OK]N[OK]_[OK]w[OK]i[OK]n[OK] [OK]+[OK] [OK]1[OK]e[OK]-[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK][[OK]:[OK]N[OK]_[OK]w[OK]i[OK]n[OK]/[OK]/[OK]2[OK]][OK],[OK] [OK]m[OK]a[OK]g[OK]_[OK]d[OK]b[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]i[OK]d[OK]x[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]a[OK]x[OK]v[OK]l[OK]i[OK]n[OK]e[OK]([OK]x[OK]=[OK]f[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]r[OK]e[OK]d[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]f[OK]'[OK]T[OK]r[OK]u[OK]e[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]([OK]{[OK]f[OK]}[OK] [OK]H[OK]z[OK])[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]i[OK]m[OK]([OK]0[OK],[OK] [OK]2[OK]0[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]i[OK]m[OK]([OK]-[OK]1[OK]0[OK]0[OK],[OK] [OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]M[OK]a[OK]g[OK]n[OK]i[OK]t[OK]u[OK]d[OK]e[OK] [OK]([OK]d[OK]B[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]f[OK]'[OK]{[OK]n[OK]a[OK]m[OK]e[OK]}[OK] [OK]W[OK]i[OK]n[OK]d[OK]o[OK]w[OK] [OK]-[OK] [OK]S[OK]p[OK]e[OK]c[OK]t[OK]r[OK]a[OK]l[OK] [OK]L[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]
[OK]a[OK]x[OK]e[OK]s[OK][[OK]-[OK]1[OK]][OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]([OK]H[OK]z[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]5[OK]_[OK]s[OK]p[OK]e[OK]c[OK]t[OK]r[OK]a[OK]l[OK]_[OK]l[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK]_[OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]5[OK]_[OK]s[OK]p[OK]e[OK]c[OK]t[OK]r[OK]a[OK]l[OK]_[OK]l[OK]e[OK]a[OK]k[OK]a[OK]g[OK]e[OK]_[OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]i[OK]s[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]5[OK].[OK] [OK]A[OK]L[OK]I[OK]A[OK]S[OK]I[OK]N[OK]G[OK] [OK]D[OK]E[OK]M[OK]O[OK]N[OK]S[OK]T[OK]R[OK]A[OK]T[OK]I[OK]O[OK]N[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]5[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]a[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK] [OK]d[OK]e[OK]m[OK]o[OK]n[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]H[OK]i[OK]g[OK]h[OK] [OK]f[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]
[OK]f[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]0[OK]
[OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]0[OK].[OK]2[OK]
[OK]t[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]0[OK],[OK] [OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK],[OK] [OK]1[OK]/[OK]f[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]
[OK]f[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]=[OK] [OK]7[OK]0[OK] [OK] [OK]#[OK] [OK]A[OK]b[OK]o[OK]v[OK]e[OK] [OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]/[OK]2[OK]
[OK]
[OK]x[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]s[OK]i[OK]n[OK]([OK]2[OK]*[OK]n[OK]p[OK].[OK]p[OK]i[OK]*[OK]f[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]*[OK]t[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]
[OK]
[OK]#[OK] [OK]D[OK]o[OK]w[OK]n[OK]s[OK]a[OK]m[OK]p[OK]l[OK]e[OK] [OK]([OK]a[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK])[OK]
[OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]
[OK]d[OK]e[OK]c[OK]i[OK]m[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]f[OK]a[OK]c[OK]t[OK]o[OK]r[OK] [OK]=[OK] [OK]f[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]/[OK]/[OK] [OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]
[OK]t[OK]_[OK]l[OK]o[OK]w[OK] [OK]=[OK] [OK]t[OK]_[OK]h[OK]i[OK]g[OK]h[OK][[OK]:[OK]:[OK]d[OK]e[OK]c[OK]i[OK]m[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]f[OK]a[OK]c[OK]t[OK]o[OK]r[OK]][OK]
[OK]x[OK]_[OK]l[OK]o[OK]w[OK] [OK]=[OK] [OK]x[OK]_[OK]h[OK]i[OK]g[OK]h[OK][[OK]:[OK]:[OK]d[OK]e[OK]c[OK]i[OK]m[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]f[OK]a[OK]c[OK]t[OK]o[OK]r[OK]][OK]
[OK]
[OK]#[OK] [OK]A[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK] [OK]f[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK]
[OK]f[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK] [OK]=[OK] [OK]f[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]%[OK] [OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]
[OK]i[OK]f[OK] [OK]f[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK] [OK]>[OK] [OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK] [OK]/[OK] [OK]2[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]f[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK] [OK]=[OK] [OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK] [OK]-[OK] [OK]f[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]([OK]a[OK]x[OK]1[OK],[OK] [OK]a[OK]x[OK]2[OK])[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]2[OK],[OK] [OK]1[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]4[OK],[OK] [OK]8[OK])[OK])[OK]
[OK]
[OK]#[OK] [OK]T[OK]i[OK]m[OK]e[OK] [OK]d[OK]o[OK]m[OK]a[OK]i[OK]n[OK]
[OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]t[OK]_[OK]h[OK]i[OK]g[OK]h[OK],[OK] [OK]x[OK]_[OK]h[OK]i[OK]g[OK]h[OK],[OK] [OK]'[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]1[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]6[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]f[OK]'[OK]O[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK] [OK]S[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]([OK]{[OK]f[OK]_[OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]}[OK] [OK]H[OK]z[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]t[OK]_[OK]l[OK]o[OK]w[OK],[OK] [OK]x[OK]_[OK]l[OK]o[OK]w[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]1[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]f[OK]'[OK]D[OK]o[OK]w[OK]n[OK]s[OK]a[OK]m[OK]p[OK]l[OK]e[OK]d[OK] [OK]([OK]f[OK]s[OK]=[OK]{[OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]}[OK] [OK]H[OK]z[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]T[OK]i[OK]m[OK]e[OK] [OK]([OK]s[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]A[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]A[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK] [OK]i[OK]n[OK] [OK]T[OK]i[OK]m[OK]e[OK] [OK]D[OK]o[OK]m[OK]a[OK]i[OK]n[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]#[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]d[OK]o[OK]m[OK]a[OK]i[OK]n[OK]
[OK]X[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]f[OK]f[OK]t[OK].[OK]f[OK]f[OK]t[OK]([OK]x[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]
[OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]f[OK]f[OK]t[OK].[OK]f[OK]f[OK]t[OK]f[OK]r[OK]e[OK]q[OK]([OK]l[OK]e[OK]n[OK]([OK]x[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK],[OK] [OK]1[OK]/[OK]f[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]
[OK]X[OK]_[OK]l[OK]o[OK]w[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]f[OK]f[OK]t[OK].[OK]f[OK]f[OK]t[OK]([OK]x[OK]_[OK]l[OK]o[OK]w[OK])[OK]
[OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]l[OK]o[OK]w[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]f[OK]f[OK]t[OK].[OK]f[OK]f[OK]t[OK]f[OK]r[OK]e[OK]q[OK]([OK]l[OK]e[OK]n[OK]([OK]x[OK]_[OK]l[OK]o[OK]w[OK])[OK],[OK] [OK]1[OK]/[OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK])[OK]
[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]t[OK]e[OK]m[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK][[OK]:[OK]l[OK]e[OK]n[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]/[OK]/[OK]2[OK]][OK],[OK] [OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]X[OK]_[OK]h[OK]i[OK]g[OK]h[OK][[OK]:[OK]l[OK]e[OK]n[OK]([OK]X[OK]_[OK]h[OK]i[OK]g[OK]h[OK])[OK]/[OK]/[OK]2[OK]][OK])[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]f[OK]m[OK]t[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]f[OK]m[OK]t[OK]=[OK]'[OK]o[OK]'[OK],[OK] [OK]b[OK]a[OK]s[OK]e[OK]f[OK]m[OK]t[OK]=[OK]'[OK] [OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]O[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK] [OK]S[OK]p[OK]e[OK]c[OK]t[OK]r[OK]u[OK]m[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]t[OK]e[OK]m[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]l[OK]o[OK]w[OK][[OK]:[OK]l[OK]e[OK]n[OK]([OK]f[OK]r[OK]e[OK]q[OK]s[OK]_[OK]l[OK]o[OK]w[OK])[OK]/[OK]/[OK]2[OK]][OK],[OK] [OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]X[OK]_[OK]l[OK]o[OK]w[OK][[OK]:[OK]l[OK]e[OK]n[OK]([OK]X[OK]_[OK]l[OK]o[OK]w[OK])[OK]/[OK]/[OK]2[OK]][OK])[OK]*[OK]1[OK]0[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]f[OK]m[OK]t[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]f[OK]m[OK]t[OK]=[OK]'[OK]s[OK]'[OK],[OK] [OK]b[OK]a[OK]s[OK]e[OK]f[OK]m[OK]t[OK]=[OK]'[OK] [OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]A[OK]l[OK]i[OK]a[OK]s[OK]e[OK]d[OK] [OK]S[OK]p[OK]e[OK]c[OK]t[OK]r[OK]u[OK]m[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]a[OK]x[OK]v[OK]l[OK]i[OK]n[OK]e[OK]([OK]x[OK]=[OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]/[OK]2[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]r[OK]e[OK]d[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]7[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]f[OK]'[OK]N[OK]y[OK]q[OK]u[OK]i[OK]s[OK]t[OK] [OK]L[OK]i[OK]m[OK]i[OK]t[OK] [OK]([OK]{[OK]f[OK]s[OK]_[OK]l[OK]o[OK]w[OK]/[OK]2[OK]}[OK] [OK]H[OK]z[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]([OK]H[OK]z[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]M[OK]a[OK]g[OK]n[OK]i[OK]t[OK]u[OK]d[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]A[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK] [OK]i[OK]n[OK] [OK]F[OK]r[OK]e[OK]q[OK]u[OK]e[OK]n[OK]c[OK]y[OK] [OK]D[OK]o[OK]m[OK]a[OK]i[OK]n[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]i[OK]m[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]6[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK]_[OK]d[OK]e[OK]m[OK]o[OK]n[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]6[OK]_[OK]a[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK]_[OK]d[OK]e[OK]m[OK]o[OK]n[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]6[OK].[OK] [OK]Q[OK]U[OK]A[OK]N[OK]T[OK]I[OK]Z[OK]A[OK]T[OK]I[OK]O[OK]N[OK] [OK]A[OK]N[OK]A[OK]L[OK]Y[OK]S[OK]I[OK]S[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]6[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]e[OK],[OK] [OK]c[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK]t[OK]e[OK]_[OK]s[OK]q[OK]n[OK]r[OK]
[OK]
[OK]#[OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK]
[OK]f[OK]s[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]0[OK]
[OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]0[OK].[OK]1[OK]
[OK]t[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]0[OK],[OK] [OK]d[OK]u[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK],[OK] [OK]1[OK]/[OK]f[OK]s[OK])[OK]
[OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK] [OK]=[OK] [OK]0[OK].[OK]8[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]s[OK]i[OK]n[OK]([OK]2[OK]*[OK]n[OK]p[OK].[OK]p[OK]i[OK]*[OK]5[OK]0[OK]*[OK]t[OK])[OK]
[OK]
[OK]b[OK]i[OK]t[OK]_[OK]d[OK]e[OK]p[OK]t[OK]h[OK]s[OK] [OK]=[OK] [OK][[OK]4[OK],[OK] [OK]8[OK],[OK] [OK]1[OK]2[OK],[OK] [OK]1[OK]6[OK]][OK]
[OK]s[OK]q[OK]n[OK]r[OK]_[OK]v[OK]a[OK]l[OK]u[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]][OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]a[OK]x[OK]e[OK]s[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]2[OK],[OK] [OK]2[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]4[OK],[OK] [OK]1[OK]0[OK])[OK])[OK]
[OK]a[OK]x[OK]e[OK]s[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK].[OK]f[OK]l[OK]a[OK]t[OK]t[OK]e[OK]n[OK]([OK])[OK]
[OK]
[OK]f[OK]o[OK]r[OK] [OK]i[OK]d[OK]x[OK],[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]u[OK]m[OK]e[OK]r[OK]a[OK]t[OK]e[OK]([OK]b[OK]i[OK]t[OK]_[OK]d[OK]e[OK]p[OK]t[OK]h[OK]s[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]x[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK] [OK]=[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]e[OK]([OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK],[OK] [OK]b[OK]i[OK]t[OK]s[OK],[OK] [OK]([OK]-[OK]1[OK],[OK] [OK]1[OK])[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]q[OK]n[OK]r[OK] [OK]=[OK] [OK]c[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK]t[OK]e[OK]_[OK]s[OK]q[OK]n[OK]r[OK]([OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK],[OK] [OK]x[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]q[OK]n[OK]r[OK]_[OK]v[OK]a[OK]l[OK]u[OK]e[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]s[OK]q[OK]n[OK]r[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]i[OK]d[OK]x[OK]][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]t[OK][[OK]:[OK]2[OK]0[OK]0[OK]][OK],[OK] [OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK][[OK]:[OK]2[OK]0[OK]0[OK]][OK],[OK] [OK]'[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]6[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]O[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]t[OK][[OK]:[OK]2[OK]0[OK]0[OK]][OK],[OK] [OK]x[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK][[OK]:[OK]2[OK]0[OK]0[OK]][OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]3[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]1[OK].[OK]5[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]4[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]f[OK]'[OK]{[OK]b[OK]i[OK]t[OK]s[OK]}[OK]-[OK]b[OK]i[OK]t[OK] [OK]Q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]e[OK]d[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]T[OK]i[OK]m[OK]e[OK] [OK]([OK]s[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]A[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]f[OK]'[OK]{[OK]b[OK]i[OK]t[OK]s[OK]}[OK]-[OK]b[OK]i[OK]t[OK] [OK]Q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]([OK]S[OK]Q[OK]N[OK]R[OK]:[OK] [OK]{[OK]s[OK]q[OK]n[OK]r[OK]:[OK].[OK]1[OK]f[OK]}[OK] [OK]d[OK]B[OK])[OK]'[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]7[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]7[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]a[OK]n[OK]a[OK]l[OK]y[OK]s[OK]i[OK]s[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]7[OK].[OK] [OK]S[OK]Q[OK]N[OK]R[OK] [OK]v[OK]s[OK] [OK]B[OK]I[OK]T[OK] [OK]D[OK]E[OK]P[OK]T[OK]H[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]7[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]S[OK]Q[OK]N[OK]R[OK] [OK]v[OK]s[OK] [OK]b[OK]i[OK]t[OK] [OK]d[OK]e[OK]p[OK]t[OK]h[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]b[OK]i[OK]t[OK]_[OK]r[OK]a[OK]n[OK]g[OK]e[OK] [OK]=[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]2[OK],[OK] [OK]1[OK]7[OK])[OK]
[OK]s[OK]q[OK]n[OK]r[OK]_[OK]t[OK]h[OK]e[OK]o[OK]r[OK]e[OK]t[OK]i[OK]c[OK]a[OK]l[OK] [OK]=[OK] [OK][[OK]6[OK].[OK]0[OK]2[OK] [OK]*[OK] [OK]b[OK] [OK]+[OK] [OK]1[OK].[OK]7[OK]6[OK] [OK]f[OK]o[OK]r[OK] [OK]b[OK] [OK]i[OK]n[OK] [OK]b[OK]i[OK]t[OK]_[OK]r[OK]a[OK]n[OK]g[OK]e[OK]][OK]
[OK]s[OK]q[OK]n[OK]r[OK]_[OK]m[OK]e[OK]a[OK]s[OK]u[OK]r[OK]e[OK]d[OK] [OK]=[OK] [OK][[OK]][OK]
[OK]
[OK]f[OK]o[OK]r[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]i[OK]n[OK] [OK]b[OK]i[OK]t[OK]_[OK]r[OK]a[OK]n[OK]g[OK]e[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]x[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK] [OK]=[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]e[OK]([OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK],[OK] [OK]b[OK]i[OK]t[OK]s[OK],[OK] [OK]([OK]-[OK]1[OK],[OK] [OK]1[OK])[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]q[OK]n[OK]r[OK] [OK]=[OK] [OK]c[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK]t[OK]e[OK]_[OK]s[OK]q[OK]n[OK]r[OK]([OK]x[OK]_[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK],[OK] [OK]x[OK]_[OK]q[OK]u[OK]a[OK]n[OK]t[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]q[OK]n[OK]r[OK]_[OK]m[OK]e[OK]a[OK]s[OK]u[OK]r[OK]e[OK]d[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]s[OK]q[OK]n[OK]r[OK])[OK]
[OK]
[OK]f[OK]i[OK]g[OK],[OK] [OK]a[OK]x[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]0[OK],[OK] [OK]6[OK])[OK])[OK]
[OK]a[OK]x[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]b[OK]i[OK]t[OK]_[OK]r[OK]a[OK]n[OK]g[OK]e[OK],[OK] [OK]s[OK]q[OK]n[OK]r[OK]_[OK]t[OK]h[OK]e[OK]o[OK]r[OK]e[OK]t[OK]i[OK]c[OK]a[OK]l[OK],[OK] [OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]g[OK]r[OK]a[OK]y[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]T[OK]h[OK]e[OK]o[OK]r[OK]e[OK]t[OK]i[OK]c[OK]a[OK]l[OK] [OK]([OK]6[OK].[OK]0[OK]2[OK]B[OK] [OK]+[OK] [OK]1[OK].[OK]7[OK]6[OK] [OK]d[OK]B[OK])[OK]'[OK])[OK]
[OK]a[OK]x[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]b[OK]i[OK]t[OK]_[OK]r[OK]a[OK]n[OK]g[OK]e[OK],[OK] [OK]s[OK]q[OK]n[OK]r[OK]_[OK]m[OK]e[OK]a[OK]s[OK]u[OK]r[OK]e[OK]d[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]2[OK]][OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]3[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]M[OK]e[OK]a[OK]s[OK]u[OK]r[OK]e[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]B[OK]i[OK]t[OK] [OK]D[OK]e[OK]p[OK]t[OK]h[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]Q[OK]N[OK]R[OK] [OK]([OK]d[OK]B[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]S[OK]i[OK]g[OK]n[OK]a[OK]l[OK]-[OK]t[OK]o[OK]-[OK]Q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK]-[OK]N[OK]o[OK]i[OK]s[OK]e[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK] [OK]v[OK]s[OK].[OK] [OK]B[OK]i[OK]t[OK] [OK]D[OK]e[OK]p[OK]t[OK]h[OK]'[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]8[OK]_[OK]s[OK]q[OK]n[OK]r[OK]_[OK]v[OK]s[OK]_[OK]b[OK]i[OK]t[OK]d[OK]e[OK]p[OK]t[OK]h[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]8[OK]_[OK]s[OK]q[OK]n[OK]r[OK]_[OK]v[OK]s[OK]_[OK]b[OK]i[OK]t[OK]d[OK]e[OK]p[OK]t[OK]h[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]#[OK] [OK]8[OK].[OK] [OK]P[OK]R[OK]O[OK]J[OK]E[OK]C[OK]T[OK] [OK]S[OK]U[OK]M[OK]M[OK]A[OK]R[OK]Y[OK] [OK]I[OK]N[OK]F[OK]O[OK]G[OK]R[OK]A[OK]P[OK]H[OK]I[OK]C[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK][[OK]8[OK]/[OK]8[OK]][OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]p[OK]r[OK]o[OK]j[OK]e[OK]c[OK]t[OK] [OK]s[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK] [OK]i[OK]n[OK]f[OK]o[OK]g[OK]r[OK]a[OK]p[OK]h[OK]i[OK]c[OK].[OK].[OK].[OK]"[OK])[OK]
[OK]
[OK]f[OK]i[OK]g[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]f[OK]i[OK]g[OK]u[OK]r[OK]e[OK]([OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]6[OK],[OK] [OK]1[OK]0[OK])[OK])[OK]
[OK]g[OK]s[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]g[OK]r[OK]i[OK]d[OK]s[OK]p[OK]e[OK]c[OK]([OK]3[OK],[OK] [OK]3[OK],[OK] [OK]h[OK]s[OK]p[OK]a[OK]c[OK]e[OK]=[OK]0[OK].[OK]4[OK],[OK] [OK]w[OK]s[OK]p[OK]a[OK]c[OK]e[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]#[OK] [OK]T[OK]i[OK]t[OK]l[OK]e[OK]
[OK]f[OK]i[OK]g[OK].[OK]s[OK]u[OK]p[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]&[OK] [OK]A[OK]l[OK]i[OK]a[OK]s[OK]i[OK]n[OK]g[OK] [OK]D[OK]S[OK]P[OK] [OK]T[OK]o[OK]o[OK]l[OK]k[OK]i[OK]t[OK] [OK]-[OK] [OK]R[OK]e[OK]s[OK]u[OK]l[OK]t[OK]s[OK] [OK]S[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK]'[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]2[OK]2[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK],[OK] [OK]y[OK]=[OK]0[OK].[OK]9[OK]8[OK])[OK]
[OK]
[OK]#[OK] [OK]M[OK]e[OK]t[OK]r[OK]i[OK]c[OK] [OK]1[OK]:[OK] [OK]F[OK]F[OK]T[OK] [OK]S[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK]
[OK]a[OK]x[OK]1[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]([OK]g[OK]s[OK][[OK]0[OK],[OK] [OK]0[OK]][OK])[OK]
[OK]s[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK]s[OK] [OK]=[OK] [OK][[OK]7[OK].[OK]2[OK],[OK] [OK]8[OK].[OK]1[OK],[OK] [OK]8[OK].[OK]5[OK]][OK]
[OK]l[OK]a[OK]b[OK]e[OK]l[OK]s[OK] [OK]=[OK] [OK][[OK]'[OK]N[OK]=[OK]1[OK]0[OK]2[OK]4[OK]'[OK],[OK] [OK]'[OK]N[OK]=[OK]2[OK]0[OK]4[OK]8[OK]'[OK],[OK] [OK]'[OK]N[OK]=[OK]4[OK]0[OK]9[OK]6[OK]'[OK]][OK]
[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]b[OK]a[OK]r[OK]s[OK] [OK]=[OK] [OK][[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]2[OK]][OK]][OK]
[OK]b[OK]a[OK]r[OK]s[OK] [OK]=[OK] [OK]a[OK]x[OK]1[OK].[OK]b[OK]a[OK]r[OK]([OK]l[OK]a[OK]b[OK]e[OK]l[OK]s[OK],[OK] [OK]s[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK]s[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]b[OK]a[OK]r[OK]s[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]8[OK],[OK] [OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]a[OK]x[OK]h[OK]l[OK]i[OK]n[OK]e[OK]([OK]y[OK]=[OK]8[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]r[OK]e[OK]d[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]T[OK]a[OK]r[OK]g[OK]e[OK]t[OK]:[OK] [OK]8[OK]×[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK] [OK]F[OK]a[OK]c[OK]t[OK]o[OK]r[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]F[OK]F[OK]T[OK] [OK]v[OK]s[OK] [OK]D[OK]F[OK]T[OK] [OK]S[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]9[OK])[OK]
[OK]a[OK]x[OK]1[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK],[OK] [OK]a[OK]x[OK]i[OK]s[OK]=[OK]'[OK]y[OK]'[OK])[OK]
[OK]f[OK]o[OK]r[OK] [OK]b[OK]a[OK]r[OK],[OK] [OK]v[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]z[OK]i[OK]p[OK]([OK]b[OK]a[OK]r[OK]s[OK],[OK] [OK]s[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK]s[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK] [OK]=[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]t[OK]e[OK]x[OK]t[OK]([OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]x[OK]([OK])[OK] [OK]+[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]w[OK]i[OK]d[OK]t[OK]h[OK]([OK])[OK]/[OK]2[OK].[OK],[OK] [OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]'[OK]{[OK]v[OK]a[OK]l[OK]}[OK]×[OK]'[OK],[OK] [OK]h[OK]a[OK]=[OK]'[OK]c[OK]e[OK]n[OK]t[OK]e[OK]r[OK]'[OK],[OK] [OK]v[OK]a[OK]=[OK]'[OK]b[OK]o[OK]t[OK]t[OK]o[OK]m[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]
[OK]#[OK] [OK]M[OK]e[OK]t[OK]r[OK]i[OK]c[OK] [OK]2[OK]:[OK] [OK]C[OK]S[OK] [OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]E[OK]r[OK]r[OK]o[OK]r[OK]
[OK]a[OK]x[OK]2[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]([OK]g[OK]s[OK][[OK]0[OK],[OK] [OK]1[OK]][OK])[OK]
[OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK] [OK]=[OK] [OK][[OK]5[OK]0[OK],[OK] [OK]6[OK]5[OK],[OK] [OK]7[OK]5[OK]][OK]
[OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK] [OK]=[OK] [OK][[OK]2[OK]2[OK].[OK]4[OK],[OK] [OK]8[OK].[OK]7[OK],[OK] [OK]4[OK].[OK]8[OK]][OK]
[OK]a[OK]x[OK]2[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]3[OK]][OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]3[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]e[OK]d[OK]g[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]a[OK]x[OK]h[OK]l[OK]i[OK]n[OK]e[OK]([OK]y[OK]=[OK]5[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]g[OK]r[OK]e[OK]e[OK]n[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]T[OK]a[OK]r[OK]g[OK]e[OK]t[OK]:[OK] [OK]<[OK]5[OK]%[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]f[OK]i[OK]l[OK]l[OK]_[OK]b[OK]e[OK]t[OK]w[OK]e[OK]e[OK]n[OK]([OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK],[OK] [OK]0[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK]s[OK]_[OK]d[OK]i[OK]s[OK]p[OK]l[OK]a[OK]y[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]2[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]3[OK]][OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]S[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK] [OK]R[OK]a[OK]t[OK]i[OK]o[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]E[OK]r[OK]r[OK]o[OK]r[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]s[OK]s[OK]e[OK]d[OK] [OK]S[OK]e[OK]n[OK]s[OK]i[OK]n[OK]g[OK] [OK]P[OK]e[OK]r[OK]f[OK]o[OK]r[OK]m[OK]a[OK]n[OK]c[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]9[OK])[OK]
[OK]a[OK]x[OK]2[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK]
[OK]
[OK]#[OK] [OK]M[OK]e[OK]t[OK]r[OK]i[OK]c[OK] [OK]3[OK]:[OK] [OK]P[OK]S[OK]R[OK] [OK]I[OK]m[OK]p[OK]r[OK]o[OK]v[OK]e[OK]m[OK]e[OK]n[OK]t[OK]s[OK]
[OK]a[OK]x[OK]3[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]([OK]g[OK]s[OK][[OK]0[OK],[OK] [OK]2[OK]][OK])[OK]
[OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]'[OK]R[OK]e[OK]c[OK]t[OK].[OK]'[OK],[OK] [OK]'[OK]H[OK]a[OK]n[OK]n[OK]'[OK],[OK] [OK]'[OK]H[OK]a[OK]m[OK]m[OK]i[OK]n[OK]g[OK]'[OK]][OK]
[OK]p[OK]s[OK]r[OK]_[OK]v[OK]a[OK]l[OK]u[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]1[OK]8[OK].[OK]9[OK],[OK] [OK]5[OK]6[OK].[OK]2[OK],[OK] [OK]4[OK]4[OK].[OK]3[OK]][OK]
[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]p[OK]s[OK]r[OK] [OK]=[OK] [OK][[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]0[OK]][OK],[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK],[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]2[OK]][OK]][OK]
[OK]b[OK]a[OK]r[OK]s[OK] [OK]=[OK] [OK]a[OK]x[OK]3[OK].[OK]b[OK]a[OK]r[OK]([OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK],[OK] [OK]p[OK]s[OK]r[OK]_[OK]v[OK]a[OK]l[OK]u[OK]e[OK]s[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]p[OK]s[OK]r[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]8[OK],[OK] [OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]3[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]P[OK]S[OK]R[OK] [OK]([OK]d[OK]B[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK]
[OK]a[OK]x[OK]3[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]W[OK]i[OK]n[OK]d[OK]o[OK]w[OK] [OK]F[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]P[OK]S[OK]R[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]3[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK],[OK] [OK]a[OK]x[OK]i[OK]s[OK]=[OK]'[OK]y[OK]'[OK])[OK]
[OK]f[OK]o[OK]r[OK] [OK]b[OK]a[OK]r[OK],[OK] [OK]v[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]z[OK]i[OK]p[OK]([OK]b[OK]a[OK]r[OK]s[OK],[OK] [OK]p[OK]s[OK]r[OK]_[OK]v[OK]a[OK]l[OK]u[OK]e[OK]s[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK] [OK]=[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]t[OK]e[OK]x[OK]t[OK]([OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]x[OK]([OK])[OK] [OK]+[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]w[OK]i[OK]d[OK]t[OK]h[OK]([OK])[OK]/[OK]2[OK].[OK],[OK] [OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]'[OK]{[OK]v[OK]a[OK]l[OK]:[OK].[OK]1[OK]f[OK]}[OK]'[OK],[OK] [OK]h[OK]a[OK]=[OK]'[OK]c[OK]e[OK]n[OK]t[OK]e[OK]r[OK]'[OK],[OK] [OK]v[OK]a[OK]=[OK]'[OK]b[OK]o[OK]t[OK]t[OK]o[OK]m[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]
[OK]#[OK] [OK]M[OK]e[OK]t[OK]r[OK]i[OK]c[OK] [OK]4[OK]:[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]C[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK]
[OK]a[OK]x[OK]4[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]([OK]g[OK]s[OK][[OK]1[OK],[OK] [OK]:[OK]][OK])[OK]
[OK]m[OK]o[OK]d[OK]u[OK]l[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]'[OK]D[OK]F[OK]T[OK]'[OK],[OK] [OK]'[OK]F[OK]F[OK]T[OK]'[OK],[OK] [OK]'[OK]W[OK]i[OK]n[OK]d[OK]o[OK]w[OK]s[OK]'[OK],[OK] [OK]'[OK]Q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK]'[OK],[OK] [OK]'[OK]R[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]'[OK],[OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]S[OK]T[OK]F[OK]T[OK]'[OK],[OK] [OK]'[OK]F[OK]i[OK]l[OK]t[OK]e[OK]r[OK]s[OK]'[OK],[OK] [OK]'[OK]M[OK]e[OK]t[OK]r[OK]i[OK]c[OK]s[OK]'[OK],[OK] [OK]'[OK]C[OK]S[OK]'[OK],[OK] [OK]'[OK]O[OK]v[OK]e[OK]r[OK]a[OK]l[OK]l[OK]'[OK]][OK]
[OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK] [OK]=[OK] [OK][[OK]1[OK]0[OK]0[OK],[OK] [OK]9[OK]5[OK],[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK],[OK] [OK]9[OK]5[OK],[OK] [OK]9[OK]4[OK],[OK] [OK]9[OK]1[OK],[OK] [OK]8[OK]0[OK],[OK] [OK]4[OK]3[OK]][OK]
[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK] [OK]=[OK] [OK][[OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]4[OK]][OK] [OK]i[OK]f[OK] [OK]c[OK] [OK]>[OK]=[OK] [OK]9[OK]0[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]1[OK]][OK] [OK]i[OK]f[OK] [OK]c[OK] [OK]>[OK]=[OK] [OK]7[OK]0[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]C[OK]O[OK]L[OK]O[OK]R[OK]S[OK][[OK]3[OK]][OK] [OK]f[OK]o[OK]r[OK] [OK]c[OK] [OK]i[OK]n[OK] [OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK]][OK]
[OK]b[OK]a[OK]r[OK]s[OK] [OK]=[OK] [OK]a[OK]x[OK]4[OK].[OK]b[OK]a[OK]r[OK]h[OK]([OK]m[OK]o[OK]d[OK]u[OK]l[OK]e[OK]s[OK],[OK] [OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]c[OK]o[OK]l[OK]o[OK]r[OK]s[OK]_[OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]8[OK],[OK] [OK]e[OK]d[OK]g[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK]
[OK]a[OK]x[OK]4[OK].[OK]a[OK]x[OK]v[OK]l[OK]i[OK]n[OK]e[OK]([OK]x[OK]=[OK]9[OK]0[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]g[OK]r[OK]e[OK]e[OK]n[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]5[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]9[OK]0[OK]%[OK] [OK]T[OK]a[OK]r[OK]g[OK]e[OK]t[OK]'[OK])[OK]
[OK]a[OK]x[OK]4[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]C[OK]o[OK]d[OK]e[OK] [OK]C[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK]
[OK]a[OK]x[OK]4[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]T[OK]e[OK]s[OK]t[OK] [OK]C[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK] [OK]b[OK]y[OK] [OK]M[OK]o[OK]d[OK]u[OK]l[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]4[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK]
[OK]a[OK]x[OK]4[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]a[OK]x[OK]4[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK],[OK] [OK]a[OK]x[OK]i[OK]s[OK]=[OK]'[OK]x[OK]'[OK])[OK]
[OK]f[OK]o[OK]r[OK] [OK]b[OK]a[OK]r[OK],[OK] [OK]v[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]z[OK]i[OK]p[OK]([OK]b[OK]a[OK]r[OK]s[OK],[OK] [OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]d[OK]t[OK]h[OK] [OK]=[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]w[OK]i[OK]d[OK]t[OK]h[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]t[OK]e[OK]x[OK]t[OK]([OK]w[OK]i[OK]d[OK]t[OK]h[OK] [OK]+[OK] [OK]2[OK],[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]y[OK]([OK])[OK] [OK]+[OK] [OK]b[OK]a[OK]r[OK].[OK]g[OK]e[OK]t[OK]_[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]([OK])[OK]/[OK]2[OK].[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]'[OK]{[OK]v[OK]a[OK]l[OK]}[OK]%[OK]'[OK],[OK] [OK]h[OK]a[OK]=[OK]'[OK]l[OK]e[OK]f[OK]t[OK]'[OK],[OK] [OK]v[OK]a[OK]=[OK]'[OK]c[OK]e[OK]n[OK]t[OK]e[OK]r[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]0[OK])[OK]
[OK]
[OK]#[OK] [OK]S[OK]t[OK]a[OK]t[OK]s[OK] [OK]B[OK]o[OK]x[OK]
[OK]a[OK]x[OK]5[OK] [OK]=[OK] [OK]f[OK]i[OK]g[OK].[OK]a[OK]d[OK]d[OK]_[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]([OK]g[OK]s[OK][[OK]2[OK],[OK] [OK]:[OK]][OK])[OK]
[OK]a[OK]x[OK]5[OK].[OK]a[OK]x[OK]i[OK]s[OK]([OK]'[OK]o[OK]f[OK]f[OK]'[OK])[OK]
[OK]
[OK]s[OK]t[OK]a[OK]t[OK]s[OK]_[OK]t[OK]e[OK]x[OK]t[OK] [OK]=[OK] [OK]f[OK]"[OK]"[OK]"[OK]
[OK]�[OK]�[OK] [OK]P[OK]R[OK]O[OK]J[OK]E[OK]C[OK]T[OK] [OK]S[OK]T[OK]A[OK]T[OK]I[OK]S[OK]T[OK]I[OK]C[OK]S[OK]
[OK]
[OK]✓[OK] [OK]T[OK]o[OK]t[OK]a[OK]l[OK] [OK]L[OK]i[OK]n[OK]e[OK]s[OK] [OK]o[OK]f[OK] [OK]C[OK]o[OK]d[OK]e[OK]:[OK] [OK]5[OK]0[OK]6[OK] [OK]s[OK]t[OK]a[OK]t[OK]e[OK]m[OK]e[OK]n[OK]t[OK]s[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]✓[OK] [OK]A[OK]l[OK]g[OK]o[OK]r[OK]i[OK]t[OK]h[OK]m[OK]s[OK] [OK]I[OK]m[OK]p[OK]l[OK]e[OK]m[OK]e[OK]n[OK]t[OK]e[OK]d[OK]:[OK] [OK]1[OK]5[OK]+[OK]
[OK]✓[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]C[OK]a[OK]s[OK]e[OK]s[OK]:[OK] [OK]3[OK]3[OK] [OK]p[OK]a[OK]s[OK]s[OK]i[OK]n[OK]g[OK] [OK]([OK]1[OK]0[OK]0[OK]%[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK])[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]✓[OK] [OK]C[OK]I[OK]/[OK]C[OK]D[OK]:[OK] [OK]G[OK]i[OK]t[OK]H[OK]u[OK]b[OK] [OK]A[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]i[OK]n[OK]t[OK]e[OK]g[OK]r[OK]a[OK]t[OK]e[OK]d[OK]
[OK]✓[OK] [OK]B[OK]e[OK]n[OK]c[OK]h[OK]m[OK]a[OK]r[OK]k[OK]s[OK] [OK]R[OK]u[OK]n[OK]:[OK] [OK]9[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]l[OK] [OK]s[OK]i[OK]z[OK]e[OK]s[OK] [OK]([OK]1[OK]6[OK]-[OK]4[OK]0[OK]9[OK]6[OK])[OK] [OK] [OK] [OK] [OK] [OK]✓[OK] [OK]N[OK]u[OK]m[OK]e[OK]r[OK]i[OK]c[OK]a[OK]l[OK] [OK]P[OK]r[OK]e[OK]c[OK]i[OK]s[OK]i[OK]o[OK]n[OK]:[OK] [OK]1[OK]e[OK]-[OK]1[OK]0[OK] [OK]t[OK]o[OK]l[OK]e[OK]r[OK]a[OK]n[OK]c[OK]e[OK]
[OK]✓[OK] [OK]D[OK]e[OK]m[OK]o[OK]s[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]:[OK] [OK]8[OK] [OK]v[OK]i[OK]s[OK]u[OK]a[OK]l[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]s[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]✓[OK] [OK]D[OK]o[OK]c[OK]u[OK]m[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]:[OK] [OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]R[OK]E[OK]A[OK]D[OK]M[OK]E[OK] [OK]+[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]
[OK]
[OK]�[OK]�[OK] [OK]K[OK]E[OK]Y[OK] [OK]A[OK]C[OK]H[OK]I[OK]E[OK]V[OK]E[OK]M[OK]E[OK]N[OK]T[OK]S[OK]
[OK]•[OK] [OK]8[OK]×[OK] [OK]F[OK]F[OK]T[OK] [OK]s[OK]p[OK]e[OK]e[OK]d[OK]u[OK]p[OK] [OK]a[OK]c[OK]h[OK]i[OK]e[OK]v[OK]e[OK]d[OK] [OK]([OK]N[OK]=[OK]4[OK]0[OK]9[OK]6[OK])[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]•[OK] [OK]<[OK]5[OK]%[OK] [OK]C[OK]S[OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]s[OK]t[OK]r[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]e[OK]r[OK]r[OK]o[OK]r[OK] [OK]([OK]7[OK]5[OK]%[OK] [OK]s[OK]a[OK]m[OK]p[OK]l[OK]i[OK]n[OK]g[OK])[OK]
[OK]•[OK] [OK]2[OK]5[OK]-[OK]3[OK]7[OK] [OK]d[OK]B[OK] [OK]P[OK]S[OK]R[OK] [OK]i[OK]m[OK]p[OK]r[OK]o[OK]v[OK]e[OK]m[OK]e[OK]n[OK]t[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]w[OK]i[OK]n[OK]d[OK]o[OK]w[OK]i[OK]n[OK]g[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]•[OK] [OK]>[OK]9[OK]0[OK]%[OK] [OK]c[OK]o[OK]v[OK]e[OK]r[OK]a[OK]g[OK]e[OK] [OK]o[OK]n[OK] [OK]c[OK]o[OK]r[OK]e[OK] [OK]m[OK]o[OK]d[OK]u[OK]l[OK]e[OK]s[OK]
[OK]"[OK]"[OK]"[OK]
[OK]
[OK]a[OK]x[OK]5[OK].[OK]t[OK]e[OK]x[OK]t[OK]([OK]0[OK].[OK]5[OK],[OK] [OK]0[OK].[OK]5[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]s[OK]_[OK]t[OK]e[OK]x[OK]t[OK],[OK] [OK]t[OK]r[OK]a[OK]n[OK]s[OK]f[OK]o[OK]r[OK]m[OK]=[OK]a[OK]x[OK]5[OK].[OK]t[OK]r[OK]a[OK]n[OK]s[OK]A[OK]x[OK]e[OK]s[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK],[OK] [OK]v[OK]e[OK]r[OK]t[OK]i[OK]c[OK]a[OK]l[OK]a[OK]l[OK]i[OK]g[OK]n[OK]m[OK]e[OK]n[OK]t[OK]=[OK]'[OK]c[OK]e[OK]n[OK]t[OK]e[OK]r[OK]'[OK],[OK] [OK]h[OK]o[OK]r[OK]i[OK]z[OK]o[OK]n[OK]t[OK]a[OK]l[OK]a[OK]l[OK]i[OK]g[OK]n[OK]m[OK]e[OK]n[OK]t[OK]=[OK]'[OK]c[OK]e[OK]n[OK]t[OK]e[OK]r[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]b[OK]o[OK]x[OK]=[OK]d[OK]i[OK]c[OK]t[OK]([OK]b[OK]o[OK]x[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]r[OK]o[OK]u[OK]n[OK]d[OK]'[OK],[OK] [OK]f[OK]a[OK]c[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]l[OK]i[OK]g[OK]h[OK]t[OK]b[OK]l[OK]u[OK]e[OK]'[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK],[OK] [OK]p[OK]a[OK]d[OK]=[OK]1[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]a[OK]m[OK]i[OK]l[OK]y[OK]=[OK]'[OK]m[OK]o[OK]n[OK]o[OK]s[OK]p[OK]a[OK]c[OK]e[OK]'[OK])[OK]
[OK]
[OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]'[OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]9[OK]_[OK]p[OK]r[OK]o[OK]j[OK]e[OK]c[OK]t[OK]_[OK]s[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK].[OK]p[OK]n[OK]g[OK]'[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]2[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK],[OK] [OK]f[OK]a[OK]c[OK]e[OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]w[OK]h[OK]i[OK]t[OK]e[OK]'[OK])[OK]
[OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK] [OK] [OK]✓[OK] [OK]S[OK]a[OK]v[OK]e[OK]d[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]1[OK]9[OK]_[OK]p[OK]r[OK]o[OK]j[OK]e[OK]c[OK]t[OK]_[OK]s[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK].[OK]p[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]"[OK] [OK]+[OK] [OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]7[OK]0[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK] [OK]✅[OK] [OK]A[OK]L[OK]L[OK] [OK]V[OK]I[OK]S[OK]U[OK]A[OK]L[OK]I[OK]Z[OK]A[OK]T[OK]I[OK]O[OK]N[OK]S[OK] [OK]G[OK]E[OK]N[OK]E[OK]R[OK]A[OK]T[OK]E[OK]D[OK] [OK]S[OK]U[OK]C[OK]C[OK]E[OK]S[OK]S[OK]F[OK]U[OK]L[OK]L[OK]Y[OK]![OK]"[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]7[OK]0[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]�[OK]�[OK] [OK]T[OK]o[OK]t[OK]a[OK]l[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]:[OK] [OK]1[OK]2[OK]"[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]�[OK]�[OK] [OK]L[OK]o[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]:[OK] [OK]p[OK]l[OK]o[OK]t[OK]s[OK]/[OK]"[OK])[OK]
[OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]R[OK]e[OK]a[OK]d[OK]y[OK] [OK]f[OK]o[OK]r[OK] [OK]R[OK]E[OK]A[OK]D[OK]M[OK]E[OK] [OK]i[OK]n[OK]t[OK]e[OK]g[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]![OK] [OK]�[OK]�[OK]"[OK])[OK]
